//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopLensApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopLensApp.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME.
        /// </summary>
        internal static string AppStartWelcome {
            get {
                return ResourceManager.GetString("AppStartWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is.
        /// </summary>
        internal static string BeginningStatement {
            get {
                return ResourceManager.GetString("BeginningStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exitCmd {
            get {
                return ResourceManager.GetString("exitCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAY &quot;HELLO&quot; TO BEGIN.
        /// </summary>
        internal static string HelloButtonMessage {
            get {
                return ResourceManager.GetString("HelloButtonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string helloCmd {
            get {
                return ResourceManager.GetString("helloCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello and welcome to ShopLens. It&apos;s time to begin your shopping..
        /// </summary>
        internal static string HelloMessage {
            get {
                return ResourceManager.GetString("HelloMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: no label names provided to product recognition model..
        /// </summary>
        internal static string NoLblError {
            get {
                return ResourceManager.GetString("NoLblError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me an item and say: what is this. I will identify the item for you..
        /// </summary>
        internal static string SeeMessage {
            get {
                return ResourceManager.GetString("SeeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string startCmd {
            get {
                return ResourceManager.GetString("startCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a webcam!.
        /// </summary>
        internal static string WebcamChooseMessage {
            get {
                return ResourceManager.GetString("WebcamChooseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The webcam is turned off!.
        /// </summary>
        internal static string WebcamTurnedOffMessage {
            get {
                return ResourceManager.GetString("WebcamTurnedOffMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is this.
        /// </summary>
        internal static string whatIsThisCmd {
            get {
                return ResourceManager.GetString("whatIsThisCmd", resourceCulture);
            }
        }
    }
}
