// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopLensWeb;

namespace MigrationsConsole.Migrations
{
    [DbContext(typeof(ShopLensContext))]
    partial class ShopLensContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("ShopLensWeb.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Discount");

                    b.Property<decimal>("FullPrice");

                    b.Property<string>("Name");

                    b.Property<int>("ShopId");

                    b.Property<int?>("ShoppingSessionId");

                    b.HasKey("ProductId");

                    b.HasIndex("ShopId");

                    b.HasIndex("ShoppingSessionId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ShopLensWeb.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ShopId");

                    b.ToTable("Shop");
                });

            modelBuilder.Entity("ShopLensWeb.ShoppingSession", b =>
                {
                    b.Property<int>("ShoppingSessionId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("UserId");

                    b.Property<string>("UserId1");

                    b.HasKey("ShoppingSessionId");

                    b.HasIndex("UserId1");

                    b.ToTable("ShoppingSession");
                });

            modelBuilder.Entity("ShopLensWeb.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Name");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShopLensWeb.Product", b =>
                {
                    b.HasOne("ShopLensWeb.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopLensWeb.ShoppingSession")
                        .WithMany("Products")
                        .HasForeignKey("ShoppingSessionId");
                });

            modelBuilder.Entity("ShopLensWeb.ShoppingSession", b =>
                {
                    b.HasOne("ShopLensWeb.User", "User")
                        .WithMany("ShoppingSessions")
                        .HasForeignKey("UserId1");
                });
#pragma warning restore 612, 618
        }
    }
}
