// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopLensWeb;

namespace MigrationsConsole.Migrations
{
    [DbContext(typeof(ShopLensContext))]
    partial class ShopLensContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShopLensWeb.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Discount");

                    b.Property<decimal>("FullPrice");

                    b.Property<string>("Name");

                    b.Property<Guid>("ShopId");

                    b.Property<Guid?>("ShoppingSessionId");

                    b.HasKey("ProductId");

                    b.HasIndex("ShopId");

                    b.HasIndex("ShoppingSessionId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ShopLensWeb.Shop", b =>
                {
                    b.Property<Guid>("ShopId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("ShopLensWeb.ShoppingSession", b =>
                {
                    b.Property<Guid>("ShoppingSessionId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<Guid>("UserId");

                    b.HasKey("ShoppingSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingSessions");
                });

            modelBuilder.Entity("ShopLensWeb.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Name");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShopLensWeb.Product", b =>
                {
                    b.HasOne("ShopLensWeb.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopLensWeb.ShoppingSession")
                        .WithMany("Products")
                        .HasForeignKey("ShoppingSessionId");
                });

            modelBuilder.Entity("ShopLensWeb.ShoppingSession", b =>
                {
                    b.HasOne("ShopLensWeb.User", "User")
                        .WithMany("ShoppingSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
